### PR TITLE
Add ukrainian translation of wizard-programmer

### PR DESCRIPTION
**Pull request by anxolerd**
@webknjaz, can you please check whether the writing style is proper?

### CODE REVIEW

**Comment by webknjaz** [comment]
On it

**Comment by jvns** [comment]
just let me know when you want me to merge this!

**Comment by webknjaz** [comment]
@jvns sure, we're still working out pieces of wording because English grammar doesn't apply to Ukrainian 1:1. This needs creative solutions :)

**Review by webknjaz — APPROVED** [review]
@jvns I think it's ready to go. If we come up with improvements, we'll just send another PR

**Pull request merged**
